sudo: required
dist: xenial
language: python

virtualenv:
   system_site_packages: true

python:
  - "3.6"

install:
  - cd python
  - pip install numpy
  - bash build_py.sh -d

script:
  - python python/tests/test.py



